### ISSUE TITLE
Lumina crash when moving plugins

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#47] opened 2015-02-04 21:08 UTC
I'm running Lumina-0.8.1.1421890927 on Openbsd-current (04/02/2015). I've added 4 plugins on the desktop (one of each). I select "unlock desktop". Then move or close one of the plugin, but whole Lumina crash. Here after the BackTrace of Lumina-DE

(gdb) bt
#0  0x000016bc21f00142 in QSettingsPrivate::actualKey () from /usr/local/lib/qt5/libQt5Core.so.0.0
#1  0x000016bc21f01c4e in QSettings::setValue () from /usr/local/lib/qt5/libQt5Core.so.0.0
#2  0x000016b93168468f in LDPluginContainer::resizeEvent () from /usr/local/bin/Lumina-DE
#3  0x000016bbc08f3440 in ?? ()
#4  0x000016bb92ea67e0 in ?? ()
#5  0x0000000000000120 in ?? ()
#6  0x000016bb00000002 in ?? ()
#7  0x000016bb92ea67f0 in ?? ()
#8  0xb8be7006243018b4 in ?? ()
#9  0x000016bc2212cf80 in _ZL12prime_deltas () from /usr/local/lib/qt5/libQt5Core.so.0.0
#10 0x000016bb779c7b80 in ?? ()
#11 0x00007f7ffffe8df0 in ?? ()
#12 0x000016bbc9324c00 in ?? ()
#13 0x000016bb779c7b80 in ?? ()
#14 0x000016bb4875f939 in QWidget::event () from /usr/local/lib/qt5/libQt5Widgets.so.0.0
#15 0xffffffffffffffff in ?? ()
#16 0x000000690000011b in ?? ()
#17 0x0000000000000052 in ?? ()
#18 0x000016bc21f8b1a9 in QMetaObject::cast () from /usr/local/lib/qt5/libQt5Core.so.0.0
#19 0x000016bb948dc400 in ?? ()
#20 0x000016bb948dc400 in ?? ()
#21 0x00007f7ffffe8df0 in ?? ()
#22 0x000016bb779c7b80 in ?? ()
#23 0x8bc8f7eba5bfdabb in ?? ()
#24 0x000016bb8b69a000 in ?? ()
#25 0x000016bb779c7b80 in ?? ()
#26 0x000016bbc9324c00 in ?? ()
#27 0x000016bbc30de400 in ?? ()
#28 0x000016bb779c7b80 in ?? ()
#29 0x00007f7ffffe8df0 in ?? ()

**Comment by beanpole135** [comment] 2015-02-05 20:12
There was a number of stability fixes that were backported to Lumina 0.8.1 right before the official release announcement of that version on the PC-BSD blog. I am willing to guess that your current package build was from before the release announcement and did not include those fixes. 

Please re-build your package and/or re-install Lumina from sources (the qt5/0.8.1 branch for the official release, or the master branch for 0.8.2-devel), and see if this problem still occurs.

**Comment by beanpole135** [comment] 2015-02-11 15:22
Closing this issue due to lack of response. 
Feel free to re-open it if this is still an issue with the current version of Lumina.

**Comment by william-os4y** [comment] 2015-02-12 14:59
Sorry for delay. I had issues to compile it. 
Finally I have Lumine-0.8.2-devel for Openbsd-current

unfortunately I have the same issues: when I unlock the desktop and shake the plugins on the desktop or close them, the system crash. 

Now I have 3 core dumps: lumina-open.core, Lumina-DE.core and fluxbox.core

Here after the backtrace of those core dumps

For lumina-open:
#0  0x0000107b0db779ea in kill () at <stdin>:2
#1  0x0000107b0dbb11c9 in abort () at /usr/src/lib/libc/stdlib/abort.c:53
#2  0x0000107a54877d86 in QMessageLogger::fatal () from /usr/local/lib/qt5/libQt5Core.so.0.0
#3  0x0000107a6e2b6617 in QXcbConnection::QXcbConnection () from /usr/local/lib/qt5/plugins/platforms/libqxcb.so
#4  0x0000014200000001 in ?? ()
#5  0x0000107a6e4159d0 in typeinfo name for INCRTransaction () from /usr/local/lib/qt5/plugins/platforms/libqxcb.so
#6  0x0000107a6e416f20 in _ZZL14ioErrorHandlerP9_XDisplayE19__PRETTY_FUNCTION__ () from /usr/local/lib/qt5/plugins/platforms/libqxcb.so
#7  0x0000107a6e414c51 in ?? () from /usr/local/lib/qt5/plugins/platforms/libqxcb.so
#8  0x0000000000000002 in ?? ()
#9  0x0000107adaaf6ae0 in ?? ()
#10 0x00007f7ffffe808c in ?? ()
#11 0x0000107b0dbb002c in malloc (size=64) at /usr/src/lib/libc/stdlib/malloc.c:1181
#12 0x00007f7ffffe7d60 in ?? ()
#13 0x0000107b10373c00 in ?? ()
#14 0x0000107b10374800 in ?? ()
#15 0x0000000000000008 in ?? ()
#16 0x0000107adaaf6ae0 in ?? ()
#17 0x00007f7ffffe808c in ?? ()
#18 0x0000107a6e2b875e in QXcbIntegration::QXcbIntegration () from /usr/local/lib/qt5/plugins/platforms/libqxcb.so
#19 0x0000107a6e2ca6fb in QXcbIntegrationPlugin::create () from /usr/local/lib/qt5/plugins/platforms/libqxcb.so
#20 0x0000107ab2c78d9f in QPlatformIntegrationFactory::create () from /usr/local/lib/qt5/libQt5Gui.so.0.0
#21 0x0000107ab2c837b6 in QGuiApplicationPrivate::createPlatformIntegration () from /usr/local/lib/qt5/libQt5Gui.so.0.0
#22 0x0000107ab2c8467d in QGuiApplicationPrivate::createEventDispatcher () from /usr/local/lib/qt5/libQt5Gui.so.0.0



for Lumina-DE:
#0  0x000011c1c7462142 in QSettingsPrivate::actualKey () from /usr/local/lib/qt5/libQt5Core.so.0.0
#1  0x000011c1c7463c4e in QSettings::setValue () from /usr/local/lib/qt5/libQt5Core.so.0.0
#2  0x000011bfc0294beb in LDPluginContainer::resizeEvent () from /usr/local/bin/Lumina-DE
#3  0x000011c2b5e9b939 in QWidget::event () from /usr/local/lib/qt5/libQt5Widgets.so.0.0
#4  0xffffffffffffffff in ?? ()
#5  0x000000e000000103 in ?? ()
#6  0x000011c2000000c9 in ?? ()
#7  0x000011c1c74ed1a9 in QMetaObject::cast () from /usr/local/lib/qt5/libQt5Core.so.0.0
#8  0x000011c212d84400 in ?? ()
#9  0x000011c212d84400 in ?? ()
#10 0x00007f7ffffe66f0 in ?? ()
#11 0x000011c2883ce700 in ?? ()
#12 0x45fe9a2ca51320ca in ?? ()
#13 0x000011c2165b5f00 in ?? ()
#14 0x000011c2883ce700 in ?? ()
#15 0x000011c255384400 in ?? ()
#16 0x000011c2759c8800 in ?? ()
#17 0x000011c2883ce700 in ?? ()
#18 0x00007f7ffffe66f0 in ?? ()
#19 0x00007f7ffffe66f0 in ?? ()
#20 0x000011c2b5fd6deb in QMdiSubWindow::event () from /usr/local/lib/qt5/libQt5Widgets.so.0.0
#21 0x000011c2b5e5d73c in QApplicationPrivate::notify_helper () from /usr/local/lib/qt5/libQt5Widgets.so.0.0
#22 0x00007f7ffffe66f0 in ?? ()


for Fluxbox:
#0  0x00000e718c97b17e in FbTk::Signal<FbTk::SigImpl::EmptyArg, FbTk::SigImpl::EmptyArg, FbTk::SigImpl::EmptyArg>::emit () from /usr/local/bin/fluxbox
#1  0x00000e718c97b66e in FbTk::Signal<FbTk::SigImpl::EmptyArg, FbTk::SigImpl::EmptyArg, FbTk::SigImpl::EmptyArg>::emit () from /usr/local/bin/fluxbox
#2  0x00000e718ca40602 in BScreen::screenNumber () from /usr/local/bin/fluxbox
#3  0x00000e718ca46c76 in FbTk::FbWindow::setAlpha () from /usr/local/bin/fluxbox
#4  0x00000e718ca5c7a0 in FbTk::FbWindow::setAlpha () from /usr/local/bin/fluxbox
#5  0x00000e718c9559ca in FbTk::CommandCreatorWithArgs<FbCommands::ClientPatternTestCmd, void> () from /usr/local/bin/fluxbox
#6  0x00000e718ca5b399 in FbTk::FbWindow::setAlpha () from /usr/local/bin/fluxbox
#7  0x00000e718ca5b457 in FbTk::FbWindow::setAlpha () from /usr/local/bin/fluxbox
#8  0x00000e718ca5c616 in FbTk::FbWindow::setAlpha () from /usr/local/bin/fluxbox
#9  0x00000e718c9559ca in FbTk::CommandCreatorWithArgs<FbCommands::ClientPatternTestCmd, void> () from /usr/local/bin/fluxbox
#10 0x00000e718c99810a in BScreen::reconfigure () from /usr/local/bin/fluxbox
#11 0x00000e718c9ee120 in AtomHandler::update () from /usr/local/bin/fluxbox
#12 0x00000e718c9e191c in Fluxbox::save_rc () from /usr/local/bin/fluxbox
#13 0x00000e7464256e49 in __cxa_finalize (dso=0x0) at /usr/src/lib/libc/stdlib/atexit.c:141
#14 0x00000e746424901e in exit (status=1) at /usr/src/lib/libc/stdlib/exit.c:57
#15 0x00000e718c9dd046 in FbTk::CommandCreator<AddWorkspaceCmd, void> () from /usr/local/bin/fluxbox
#16 0x00000e746aa89842 in _XIOError () from /usr/X11R6/lib/libX11.so.16.0
#17 0x00000e746aa87bfc in _XReply () from /usr/X11R6/lib/libX11.so.16.0
#18 0x00000e746aa749a1 in XListInstalledColormaps () from /usr/X11R6/lib/libX11.so.16.0

**Comment by beanpole135** [comment] 2015-02-12 15:53
The lumina-open and fluxbox crashes are probably caused by X closing down after the desktop crashes (it is normal for a login manager to restart X after a desktop session ends).

The Lumina-DE crash is interesting, because it appears to be something with saving the plugin location to the file.
[quote]
#0 0x000011c1c7462142 in QSettingsPrivate::actualKey () from /usr/local/lib/qt5/libQt5Core.so.0.0
#1 0x000011c1c7463c4e in QSettings::setValue () from /usr/local/lib/qt5/libQt5Core.so.0.0
#2 0x000011bfc0294beb in LDPluginContainer::resizeEvent () from /usr/local/bin/Lumina-DE
[/quote]
LDPluginContainer (Lumina Desktop Plugin Container) simply listens for resize events and saves that new position/size to the settings file (so it can be restored to the same position/size on later logins). 

Let me add a small delay/single-instance check to that routine here soon so that it does not run too often or interfere with the container getting removed.

**Comment by beanpole135** [comment] 2015-02-12 16:12
Ok, I just commited a couple fixes for the desktop plugin container. See if that works for you now.

**Comment by william-os4y** [comment] 2015-02-12 18:09
Heeee heee  it works now :-). 

you are quick and efficient !!!!

many tanks.

**Comment by william-os4y** [comment] 2015-02-15 12:19
Unfortunately, I'm still able to crash Lumina. 
when the desktop is unlocked, you shake a plugin's screen and you close it immediately. 
If you close an otherone (not shaked), or if you wait +-20 seconds, the crash does not occurs. 

Does this only happen on OpenBSD ? Are you able to reproduce it on a FreeBSD machine ?

regards

**Comment by beanpole135** [comment] 2015-02-16 13:22
Sorry about that: Forgot to disable the 1-second sync timer when the plugin is closed[1]. 
Basically, the plugin starts/restarts a 1-second timer every time it is moved which then runs the save settings routine after that timer finishes (to prevent spamming the file on every movement). The problem was that I forgot to stop that timer when the plugin is removed, causing it to crash <1second after plugin removal when it tries to save the non-existent settings to the non-existant file.

[1] https://github.com/pcbsd/lumina/commit/bce4b68794a208f390aaf39e5d3483e5d12ac73d

**Closed by beanpole135** 2015-02-16 13:22 UTC

**Comment by william-os4y** [comment] 2015-02-17 18:03
I confirm, it works perfect. Thanks.
