### ISSUE TITLE
Icons in Tray are not visible

### ISSUE THREAD

**Issue by mike-pt** [pcbsd/lumina#52] opened 2015-02-19 21:50 UTC
I just update to the "master" version and noticed that the pidgin icon was just showing a "square", tested with chroimum too and I see the same.

**Comment by beanpole135** [comment] 2015-02-19 22:14
Are you running FreeBSD-Current (will become version 11.x) ? I had somebody tell me something similar on IRC, and he specifically mentioned it only happened on FreeBSD-current.

**Comment by mike-pt** [comment] 2015-02-19 22:18
Actually yes!

**Comment by beanpole135** [comment] 2015-02-19 22:26
Good! That helps me narrow down the cause. I am going to spin up a PC-BSD 11-Current image here soon so I can test it out and see what the differences are. My guess is that something in X11 has changed, so I need to adjust the tray embedding routine to account for it (or it is a bug in the new version X11 itself, 11-current *is* still highly experimental.... :-)

**Comment by mike-pt** [comment] 2015-02-20 00:21
Yeah I should have posted that in the first place... totally forgot, and since I've upgrade to 11 just a few days ago that's probably the cause.

**Comment by mike-pt** [comment] 2015-02-20 01:13
Btw running current on another laptop and I don't see the issue:

So either the update to lumina:
lumina-0.8.1.1422648977,1

Or freebsd:
FreeBSD hpbsd 11.0-CURRENT FreeBSD 11.0-CURRENT #7 b6a4dfa(master)-dirt

Intruduced the regression (Im running a more recent version on the laptop I notice it)
FreeBSD r2d2 11.0-CURRENT FreeBSD 11.0-CURRENT #8 r278930+0a219ba

**Comment by beanpole135** [comment] 2015-02-20 13:58
Great! Looks like it was probably just an issue with X11 in that build of FreeBSD-11, and was fixed in later revisions. I guess running into things like this is to be expected with the bleeding-edge/unstable versions of FreeBSD... :-)

Before I close this bug: could you report the build dates of the broken/working versions of FreeBSD 11? That way anyone else looking this up can know what minimum version of FreeBSD 11 they need to be running to fix the issue.

Thanks!

**Comment by mike-pt** [comment] 2015-02-21 04:36
I'm using git and seems the first one is odd for a release number matching svn... weired... In any case I'm updating me src and ports again to see if this is gone (maybe I get lucky)

**Comment by mike-pt** [comment] 2015-03-13 00:25
I stil get this issue in CURRENT, already mailing the list but no luck so far... I did notice this in lumina's runtime.log:

Debug: New System Tray App: 27263976
Debug: Window Property Event
Debug: SysTray: Damage Event
Debug: -- Icon size mismatch
Debug: -- Icon size mismatch
Debug: -- Icon size mismatch
Debug: -- Icon size mismatch
Debug: SysTray: Damage Event
Debug: SysTray: Damage Event
Debug: SysTray: Damage Event
Debug: SysTray: Damage Event
Debug: SysTray: Configure Event
Debug: SysTray: Damage Event
Debug: -- Icon size mismatch
Debug: SysTray: Damage Event


Does it help?

**Comment by beanpole135** [comment] 2015-03-13 08:26
Are you using the PC-BSD release of 11-Current?
PC-BSD put an experimental patch into Qt5 for some system tray icon changes so that tray apps would display properly in the MATE desktop - but now we are seeing system tray issues in many other desktops (Lumina and XFCE for example) and we think that patch might be the problem. We are still looking into this and trying to figure out whether we should just remove that patch (if that fixes it), or if there is some other change in X on FreeBSD11-Current that is causing the issues.

FYI: Those "Damage Event"s are the event that tells the tray icon to repaint (due to an icon change of some kind), and the "Icon size mismatch" is just a warning that the current tray application icon does not "fit" the size of the panel exactly and it sends a request to the tray app to adjust it's size appropriately. Those are both just cosmetic/debugging output - no need to worry about it. I have actually put a number of additional debugging statements for the tray icon painting routine in the source tree recently - so if you rebuild Lumina on your 11 system you might get some warnings about empty tray icons and such which *would* be useful.

**Comment by mike-pt** [comment] 2015-03-14 16:28
FreeBSD but I've mailed the list last week and Ken did mention that change, suggesting it would fix the issue, but this is already on ports and I'm already using the patch...

However now that you mention it, maybe its the patch that's breaking things for lumina...

Assuming this is the one:
https://svnweb.freebsd.org/ports?view=revision&revision=379187

I can test without the patch and rebuild qt5-gui, would I need to rebuild lumina too?

**Comment by beanpole135** [comment] 2015-03-14 21:02
That is the patch all right - I did not realize it had already made it's way into FreeBSD proper.....
Since the patch is used in building the Qt runtime libraries, you should not need to rebuild Lumina as well. You might need to reboot your computer after rebuilding the Qt libraries just to ensure that your don't have the old libraries being used from memory though.

**Comment by mike-pt** [comment] 2015-03-14 23:26
Actually scratch that.. the other laptop I have with CURRENT as the same port version and works fine, the issue must be in the FreeBSD code, not ports, I've posted that before but was just not thinking about it and just focused on the patch but It doesn't even matter to the case...


My bad

Some change after this:
FreeBSD hpbsd 11.0-CURRENT FreeBSD 11.0-CURRENT #7 b6a4dfa(master)-dirty: Tue Feb 10 22:21:46 WET 2015 

Caused a regression.... problem is finding out what it might be.

In any cause I've updated (git pull) and rebuillt lumina and I'm rebooting to see if I get more debug info

**Comment by mike-pt** [comment] 2015-03-15 17:42
For reference after reboot, this is all I get opening pidgin (in runtime.log any other log I should check?)

Debug: Window Property Event
Debug: Launch Application: "/usr/local/share/applications/pidgin.desktop"
Debug: Tray List Changed
Debug: New System Tray App: 20971581
Debug: Window Property Event
Debug: Window Property Event
Debug: SysTray: Damage Event
Debug: -- Icon size mismatch
Debug: -- Icon size mismatch
Debug: -- Icon size mismatch
Debug: SysTray: Configure Event
Debug: SysTray: Damage Event
Debug: Window Property Event
Debug: Adjust Window Geometry: "Pidgin" true
Debug:  - On Screen: 0
Debug: Window Property Event
Debug: Window Property Event
Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2323, resource id: 0, major code: 20 (GetProperty), minor code: 0
Debug: SysTray: Damage Event
Debug: SysTray: Configure Event
Debug: SysTray: Damage Event
Debug: -- Icon size mismatch
Debug: SysTray: Damage Event
Debug: -- Icon size mismatch
Debug: SysTray: Configure Event
Debug: SysTray: Damage Event
Debug: SysTray: Damage Event
Debug: SysTray: Damage Event
Debug: SysTray: Damage Event
Debug: Window Property Event

**Comment by beanpole135** [comment] 2015-03-15 21:44
Well, that means that Lumina *is* getting an icon from the system tray (since I don't see all those errors) - so the image fetching routines are working. This probably implies that either the image that was retrieved is empty/blank, or that there is something in the QPainter itself which cannot paint that image onto the screen (which is highly unlikely - since every other part of the desktop gets painted just fine).

**Comment by mike-pt** [comment] 2015-03-16 01:05
@beanpole135 makes sense... I checked the icons however and all seems fine...

while searching I found some references of prior bugs with icons and qt5.... I wonder if there's a way to test with qt4... even if with just some example app (while research that)

In any case I also notice the icons for the folder view and lumina-fm seem bigger than before, at least the "height" doesn't seem right and its showing on top of the text for wither the folder names (in lumina-fm) or the desktop icon names... (I had noticed it before in lumina-fm but totally forgot, so its not a recent change and I wonder if this is related somehow)

**Comment by mike-pt** [comment] 2015-03-16 15:18
the lumina-fm icon size issue is reported in #72.

As for the tray issue, it really seems to be some change in freebsd kernel/module, but what could it be? drm? If I can have at least a hint where to look I can maybe do some bisect

**Comment by mike-pt** [comment] 2015-03-27 04:55
@beanpole135 have you had any chance to test/look deeper into this in current?

I can't seem to find why this fails and it seem o be ok in other DE's (not kde as it takes a huge time to build and I can't get it from pkgng), it does work fine on MATE.

Also when running alltray I see the icons, which proof (if any more evidence was needed) that it can be anything wrong with the icon files, so maybe it is an issue with qt5 or Lumina?

**Comment by beanpole135** [comment] 2015-03-27 13:06
Yes, I tracked down the cause, and it appears to be something in the xcomposite extension on FreeBSD 11 which is causing the issue.
If I disable the "XCompositeRedirectWindow()" line in the system tray embedding routine (LuminaX11.cpp, line 462), then the tray icon shows up fine (although with a black background because the compositing was turned off). I am still trying to figure out if this is an issue with X11 in FreeBSD 11, or if there is something I can do in Lumina to make it "just work". I am converting that routine to use the XCB library instead of XLib/XComposite at the moment to see if that makes a difference - I will report back later with any progress.

**Comment by mike-pt** [comment] 2015-03-28 05:25
Just updating (git pull) and giving this changes a try...

I noticed another issue in the process:

```
commit df64525b92c1220c0b3950e57d73d6dc729d3388
Author: Ken Moore <ken@pcbsd.org>
Date:   Fri Mar 27 16:48:31 2015 -0400

    Add thumbnail support for image files in the desktopview plugin.
    Also update the port makefile for FreeBSD so that has the proper gstreamer plugins installed for audio support.

diff --git a/port-files/Makefile b/port-files/Makefile
index d5c23b2..8454834 100644
--- a/port-files/Makefile
+++ b/port-files/Makefile
@@ -30,7 +30,9 @@ MULTIMEDIA_DESC=      Install multimedia support backend (gstreamer)
 .include <bsd.port.options.mk>
 
 .if ${PORT_OPTIONS:MMULTIMEDIA}
-RUN_DEPENDS+=  gstreamer-plugins>=0:${PORTSDIR}/multimedia/gstreamer-plugins
+RUN_DEPENDS+=  gstreamer-plugins-core>=0:${PORTSDIR}/multimedia/gstreamer-plugins-core \
+               gstreamer-plugins-ogg>=0:${PORTSDIR}/multimedia/gstreamer-plugins-ogg \
+               gstreamer-plugins-vorbis>=0:${PORTSDIR}/multimedia/gstreamer-plugins-vorbis \ <----- this '\' is breaking the port build cause it expects another line ofc...
I'm not sure if the line is missing, or if its just the "\" that is there by accident?
 .endif
```

**Comment by beanpole135** [comment] 2015-03-28 13:15
Thanks for pointing that out! 
I just removed that slash, one of the hazards of copy/paste... :-)

BTW: From all my testing it appears that the system tray icon issues should be solved now. I switched the window-image function over to the Qt version and it seems to work fine now (still not sure why, maybe it has better fallback/alternate approaches?).

**Closed by beanpole135** 2015-03-28 13:15 UTC

**Comment by mike-pt** [comment] 2015-03-28 16:12
Just liked to confirm its working here after the update, it was working before, so I still think something changed in some 11-CURRENT commit we will probably won't find, or stump into later while fixing something else? :D

Anyway thanks for fixing it at lumina's side :)

**Comment by beanpole135** [comment] 2015-03-30 14:10
Yeah, I am still of the opinion that something changed in FreeBSD 11 as well - but at least Lumina does not care any more... :-)
