### ISSUE TITLE
No window focused after closing menus

### ISSUE THREAD

**Issue by Mitlik** [pcbsd/lumina#142] opened 2015-08-03 22:13 UTC
Lumina leaves no window in focus after closing a menu, even when one would be expected to have focus.

__Package version:__ Lumina 0.8.6-Release
__Steps to recreate:__
1.  Open a program that is easy to interact with via keyboard  (e.g. text editor or terminal) and give it focus
2.  Open a menu from the panel or the desktop
3.  Close the menu via one of the use cases below
4.  Try to interact with the window expected to have focus

Use case | Actual behavior
---------|----------------
Open new panel/desktop menu | Open new menu, no window focus (matches expected)
Click desktop whitespace | No window focus
Click panel whitespace | No window focus
Single click window | No window focus
Keyboard escape or right-click to close menu | No window focus (unless Alt+Tab then it returns to last window)

Use case | Expected behavior
---------|------------------
Open new panel/desktop menu | Open new menu, no window focus (matches actual)
Click desktop whitespace | No window focus, but no desktop focus either
Click panel whitespace | Return focus to last item
Single click window | Focus on clicked window
Keyboard escape or right-click to close menu | Return focus to last item

__Additional information:__
*  __OS:__ Debian Jessie (stable)
*  __Kernel:__ Linux 3.16.0-4-686-pae # 1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) i686 GNU/Linux
*  __Hardware:__ Intel Atom (dual core)

I am pretty sure I had another use case worked out, but the first submit was lost.

**Comment by beanpole135** [comment] 2015-09-16 15:34
OK, I think I have this all fixed up: but it will not match your "expected behavior" because of a misunderstanding of menu operations/priorities. A menu is a special type of window in that it is transient/temporary, and it is only open/visible while it has activation priority. Any click outside of the menu is supposed to be treated as a "cancel" of the menu, without touching any other windows/buttons underneath the mouse click (which prevents all sorts of accidental operations by the user).

With the new fixes[1], any time a panel sub-menu is closed it will do the following:
If the mouse is over the panel it will keep focus on the panel (for hidden panels this is particularly important). If not, it will hide the panel (if necessary) and re-activate the previously-active window (or the newly-active window - depending on what operation the user might have triggered).

[1] https://github.com/pcbsd/lumina/commit/470d9b82a7269cfec9e6b9d79074deff7bb62dc9

**Closed by beanpole135** 2015-09-16 15:34 UTC
